# Variables

$terminal = kitty                                                           
$fileManager = dolphin                                                      
$menu = rofi -show drun -show-icons -theme ~/.config/rofi/config.rasi       
$statusbar = ~/.config/waybar/launch.sh                                     
$wallswitch = ~/.config/hypr/wallpaper.sh                                   
$walldefault = ~/.config/hypr/default-wall.sh                               
                                                                              
exec-once = $terminal                                                       
exec-once = $statusbar                                                      
exec-once = $walldefault                                                    
exec-once = systemctl --user start hyprpolkitagent                          
exec-once = dunst                                                           
exec = dunstify "i use arch btw" 
