# Variables

$terminal = kitty                                                           
$fileManager = dolphin                                                      
$menu = rofi -show drun -show-icons -theme ~/.config/rofi/config.rasi       
$statusbar = ~/.config/waybar/launch.sh                                     
$wallswitch = ~/.config/hypr/wallpaper.sh                                   
$walldefault = ~/.config/hypr/default-wall.sh                               
