cursor            #99ccfa
cursor_text_color #ffffff

foreground            #e0e2e8
background            #0b0f12
selection_foreground  #23323f
selection_background  #b8c8da
url_color             #b8c8da

#: black 000000 767676
color0  #101418
color8  #313539
#: red cc0403 f2201f
color1  #04101c
color9  #155ea4
#: green 19cb00 23fd00
color2  #b8c8da
color10 #d4e4f6
#: yellow cecb00 fffd00
color3  #d2bfe7
color11 #eddcff
#: blue 0d73cc 1a8fff
color4  #084b72
color12 #99ccfa
#: magenta cb1ed1 fd28ff
color5  #394857
color13 #b8c8da
#: cyan 0dcdcd 14ffff
color6  #4e4161
color14 #d2bfe7
#: white dddddd ffffff
color7  #c2c7ce
color15 #e0e2e8

mark1_foreground #001d31
mark1_background #cce5ff
mark2_foreground #0d1d2a
mark2_background #d4e4f6
mark3_foreground #221533
mark3_background #eddcff

active_tab_foreground #003351
active_tab_background #99ccfa
inactive_tab_foreground #cce5ff
inactive_tab_background #084b72

active_border_color #99ccfa
inactive_border_color #003351
# bell_border_color #ff5a00
